[package]
name = "srp"
version = "0.5.0"
edition = "2018"
authors = ["RustCrypto Developers"]
license = "MIT OR Apache-2.0"
description = "Secure Remote Password (SRP) protocol implementation"
documentation = "https://docs.rs/srp"
repository = "https://github.com/RustCrypto/PAKEs"
keywords = ["crypto", "pake", "authentication"]
categories = ["cryptography", "authentication"]

[dependencies]
num-bigint = "0.4"
generic-array = "0.14"
digest = "0.9"
lazy_static = "1.2"
subtle = "2.4"

[dev-dependencies]
rand = "0.6"
sha2 = "0.9"
sha-1 = "0.9"
hex = "0.4"
num-traits = "0.2"

[badges]
travis-ci = { repository = "RustCrypto/PAKEs" }
